branches:
  only:
  - master
  - stable
language: java
jdk:
- openjdk11
dist: focal
before_install:
install:
- mvn clean install -Dgpg.skip=true
before_script: 
script: 
after_success:
- "./ci/deploy.sh"
after_failure:
